wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.11.0
    start_time: 1679435402.026436
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 5
      - 23
      - 24
      4: 3.11.0
      5: 0.14.0
      8:
      - 5
